### ISSUE TITLE
glob support

### ISSUE THREAD

**Issue by benderTheCrime** [bezoerb/asset-resolver#82]
Hi,

I came here as a result of working with https://github.com/bezoerb/postcss-image-inliner which you seem to have authored as well. Is it possible to make this package support globs? 

Right now, I have to make my source 

```
[
    'dir1/images/',
    'dir2/images/',
    ...
]
```

which is not a very convenient practice. I suppose I could use a globber and then pass the result through to asset-resolver, but it may be beneficial to just have support for globs in the package itself so that instead of the above, I could do:

```
[ '**/images/' ]
```

**Comment by bezoerb** [comment]
@benderTheCrime just added glob support in [v0.2.0](https://github.com/bezoerb/asset-resolver/releases/tag/v0.2.0)

**Comment by benderTheCrime** [comment]
I'll take a look, thanks! Will close this.
